apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
        - name: training-deployment
          image: training-deployment:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/data"
              name: shared-data
            - mountPath: "/mnt/model_storage"
              name: model-storage
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: model-pvc
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: training-service
spec:
  type: NodePort
  selector:
    app: training
  ports:
    - protocol: TCP
      port: 5002  
      targetPort: 5002
      nodePort: 30008  # Fixed port for external access