apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: application:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-data
          mountPath: /data
        ports:
        - containerPort: 5000
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-pvc
        # emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort