apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.4.1
        args:
        - "mlflow"
        - "server"
        - "--backend-store-uri=sqlite:///mlflow.db"
        - "--default-artifact-root=/mlflow-artifacts"
        - "--host=0.0.0.0"
        - "--port=5004"
        ports:
        - containerPort: 5004
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow-artifacts
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: NodePort