apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-train
  template:
    metadata:
      labels:
        app: model-train
    spec:
      containers:
        - name: model-train
          image: model-train:latest
          volumeMounts:
            - mountPath: "/data"
              name: shared-data
            - mountPath: "/model-storage"
              name: model-storage
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc