apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-train
  template:
    metadata:
      labels:
        app: model-train
    spec:
      containers:
        - name: model-train
          image: model-train:latest
          volumeMounts:
            - mountPath: "/mnt/data"
              name: shared-data
            - mountPath: "/mnt/model_storage"
              name: model_storage
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: model_storage
          persistentVolumeClaim:
            claimName: model-pvc