apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - name: inference
          image: inference:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/data" 
              name: shared-data 
          ports:
            - containerPort:5003    
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: NodePort

